# Generated by Django 2.2.16 on 2022-08-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220807_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
